Geom_path of indicators change
========================================================



```{r }
library(ggplot2)
library(reshape)
Baseline <- c(1,1,1,1,1,1,1,1) 
#Baseline value for indicators
Current <- c(1.73,0.58,1,0.92,1.02,1.54,0.19,0.8) 
average <- mean(Current)
#Current value relatively to baseline value
Indicators <- c("Invasive alien species","Rice diversity","Multifunctionality", "Food sovereignty", "Nutrition diversity", "Profitability", "TEP", "Primogeniture")
#Eight indicators
id <- 1:8
df <- data.frame(Baseline, Current, Indicators,id)
dfm <- melt(df, id.var = c("id", "Indicators"))
dpsir <- c("Pressure", "State", "State", "Impact", "Impact", "Impact", "Response", "Response")
dfm$dpsir <- dpsir
dfm$dpsir <- factor(dfm$dpsir,
         levels = c("Pressure", "State", "Impact", "Response"))
#Order the dpsir stages by PSIR instead of alphabetically
```

Creating the plot

```{r}
gg <- ggplot(dfm, aes(variable, value, group = id, colour = Indicators)) +
  geom_path(size = 2) + labs(x = "", y="Relative value")+ theme_bw(base_size=13)
gg
```

Changing colors, with green being high increase and red being high decline
```{r}

mypalette <- c("#FFA07A", "#006400", "#98FB98", "#90EE90", "#FF7F50",  "#228B22", "#FF6347", "#FF0000")
#Create a color palette

gg2<-gg + scale_colour_manual(values = mypalette, breaks=c("Invasive alien species","Profitability", "Nutrition diversity","Multifunctionality", "Food sovereignty", "Primogeniture", "Rice diversity", "TEP"))
#Reorder the the indicators so that indcators come in the order to PSIR stages
gg2
```

Divide plots by DIPSIR Stages

```{r}
gg3 <- gg2 + facet_grid(dpsir~.)
gg3
```


**Adding an average line**

```{r}

average <- mean(c(0.58,1,0.92,1.02,1.54,0.8,0.19,0.97)) #average of indicators ecluding pressures
Baseline <- c(1,1,1,1,1,1,1,1,1) 
#Baseline value for indicators
Current <- c(1.73,0.58,1,0.92,1.02,1.54,0.8,0.19,0.88) 
average <- mean(Current)
#Current value relatively to baseline value
Indicators <- c("Invasive alien species","Rice diversity","Multifunctionality", "Food sovereignty", "Nutrition diversity", "Profitability", "Primogeniture", "TEP", "Average")

#Eight indicators
id <- 1:9
df <- data.frame(Baseline, Current, Indicators,id)
dfm <- melt(df, id.var = c("id", "Indicators"))
dpsir <- c("Pressure", "State", "State", "Impact", "Impact", "Impact", "Response", "Response","Average","Pressure", "State", "State", "Impact", "Impact", "Impact", "Response", "Response","Average")
dfm$dpsir <- dpsir
dfm$dpsir <- factor(dfm$dpsir,
         levels = c("Pressure", "State", "Impact", "Response", "Average"))
dfm$Indicators <- factor(dfm$Indicators,
         levels = c("Invasive alien species","Rice diversity","Multifunctionality", "Food sovereignty", "Nutrition diversity", "Profitability", "Primogeniture", "TEP", "Average"))
gg <- ggplot(dfm, aes(variable, value, group = id, colour = Indicators)) +
  geom_path(size = 2) + labs(x = "", y="Relative value")+ theme_bw(base_size=15)
gg
```

Changing color

```{r}
mypalette <- c("#008000", #IAS
               "#FF6347", #Rice Diversity
               "#C0C0C0", #Multifunctionaliy
               "#FFCCCC", #Food Sov
               "#98FB98", #Nutrition
               "#32CD32", #Profi
               "#FFA07A", #Primo
               "#FF0000", #TEP
               "#000000")#Average
#Create a color palette

gg2<-gg + scale_colour_manual(values = mypalette)
#Reorder the the indicators so that indcators come in the order to PSIR stages
gg2

gg3 <- gg2 + facet_grid(dpsir~.)
gg3
```